/******************************************************************************
 * Copyright (c) 2022-2022 by ZEEKR. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * @Brief:Fault source
 * @Author:e-Pan.Cheng
 * @Date:
 *****************************************************************************/
#ifndef __FAULTNAME_TO_FAULTID_HPP__
#define __FAULTNAME_TO_FAULTID_HPP__

namespace fault
{
namespace common
{
//FM_CAMERA_LONG_FRONT_XXX    5001-5500

//FM_CAMERA_WIDE_FRONT_XXX    5501-6000

//FM_CAMERA_SIDE_LEFT_FRONT_XXX    6001-6500

//FM_CAMERA_SIDE_RIGHT_FRONT_XXX    6501-7000

//FM_CAMERA_SIDE_LEFT_REAR_XXX    7001-7500

//FM_CAMERA_SIDE_RIGHT_REAR_XXX    7501-8000

//FM_CAMERA_REAR_XXX    8001-8500

//FM_CAMERA_SUR_FRONT_XXX    8501-9000
constexpr int FM_PERCP_PARKPERCP_FRONT_SURROUND_IMAGE_DIRT_IPMNN = 8501;

//FM_CAMERA_SUR_RIGHT_XXX    9001-9500
constexpr int FM_PERCP_PARKPERCP_RIGHT_SURROUND_IMAGE_DIRT_IPMNN = 9001;

//FM_CAMERA_SUR_LEFT_XXX    9501-10000
constexpr int FM_PERCP_PARKPERCP_LEFT_SURROUND_IMAGE_DIRT_IPMNN = 9501;

//FM_CAMERA_SUR_REAR_XXX    10001-10500
constexpr int FM_PERCP_PARKPERCP_REAR_SURROUND_IMAGE_DIRT_IPMNN = 10001;

//FM_SMART_CAMERA_XXX    11001-11500

//FM_LIDAR_FRONT_XXX    12001-12500

//FM_LIDAR_SIDE_LEFT_XXX    13001-13500

//FM_LIDAR_SIDE_RIGHT_XXX    14001-14500

//FM_RADAR_FRONT_XXX    15001-15500

//FM_RADAR_SIDE_LEFT_FRONT_XXX    16001-16500

//FM_RADAR_SIDE_RIGHT_FRONT_XXX    17001-17500

//FM_RADAR_SIDE_LEFT_REAR_XXX    18001-18500

//FM_RADAR_SIDE_RIGHT_REAR_XXX    19001-19500

//FM_USS_FLC_XXX    20001-20100

//FM_USS_FRC_XXX    20101-20200

//FM_USS_FLM_XXX    20201-20300

//FM_USS_FRM_XXX    20301-20400

//FM_USS_FLS_XXX    21001-21500

//FM_USS_FRS_XXX    22001-22500

//FM_USS_RLS_XXX    23001-23500

//FM_USS_RRS_XXX    24001-24500

//FM_USS_RLC_XXX    25001-25100

//FM_USS_RRC_XXX    25101-25200

//FM_USS_RLM_XXX    25201-25300

//FM_USS_RRM_XXX    25301-25400

//FM_PDCM_XXX    26001-26500

//FM_ADPU_XXX    27001-27500

//FM_SOC1_NV_XXX    28001-28500

//FM_SOC1_PLT_XXX    29001-29500
constexpr int FM_SOC1_SYSTEM_MEMORY_OVER_USED = 29001;
constexpr int FM_SOC1_SYSTEM_MEMORY_OUT_USED = 29002;
constexpr int FM_SOC1_SYSTEM_CPU_OVER_USED = 29003;
constexpr int FM_SOC1_SYSTEM_CPU_OUT_USED = 29004;
constexpr int FM_SOC1_DISK_OVER_USED = 29005;
constexpr int FM_SOC1_DISK_OUT_USED = 29006;
constexpr int FM_SOC1_FILESYSTEM_RUN_ERROR = 29007;
constexpr int FM_SOC1_FILESYSTEM_START_ERROR = 29008;
constexpr int FM_SOC1_SYSTEM_HANDLER_EXCEPTION = 29009;
constexpr int FM_SOC1_SYSTEM_CLOCK_SYNC_ERROR = 29010;
constexpr int FM_SOC1_SYSTEM_CLOCK_SYNC_CHANGE_ERROR = 29011;
constexpr int FM_SOC1_SYSTEM_TIMER_OUT_OF_SYNC = 29012;
constexpr int FM_SOC1_NETWORK_THROUGHPUT_ERROR = 29013;
constexpr int FM_SOC1_PROCESS_COREDUMP_ERROR = 29018;
constexpr int FM_SOC1_THREAD_EXCEPTION_ERROR = 29020;
constexpr int FM_SOC1_DISCONNECT_ERROR = 29024;
constexpr int FM_ROS_SOC1_PUB_FAILED = 29101;
constexpr int FM_ROS_SOC1_SUB_FAILED = 29102;
constexpr int FM_ROS_SOC1_INCONSISTENT = 29103;
constexpr int FM_ROS_SOC1_QOS_INCOMPATABLE = 29104;
constexpr int FM_ROS_SOC1_SAMPLE_LOST = 29105;
constexpr int FM_ROS_SOC1_SAMPLE_REJECTED = 29106;
constexpr int FM_ROS_SOC1_PUB_LIVELINESS_CHANGED = 29107;
constexpr int FM_ROS_SOC1_SUB_DOWN = 29108;
constexpr int FM_ROS_SOC1_PUB_DOWN = 29109;
constexpr int FM_ROS_SOC1_PUB_DEADLINE_MISSED = 29110;
constexpr int FM_ROS_SOC1_SUB_DEADLINE_MISSED = 29111;
constexpr int FM_ROS_SOC1_LATENCY_HEIGH = 29112;

//FM_SOC1_OS_XXX    29501-29800

//FM_SOC2_NV_XXX    30001-30500

//FM_SOC2_PLT_XXX    31001-31500
constexpr int FM_SOC2_SYSTEM_MEMORY_OVER_USED = 31004;
constexpr int FM_SOC2_SYSTEM_MEMORY_OUT_USED = 31005;
constexpr int FM_SOC2_SYSTEM_CPU_OVER_USED = 31006;
constexpr int FM_SOC2_SYSTEM_CPU_OUT_USED = 31007;
constexpr int FM_SOC2_DISK_OVER_USED = 31008;
constexpr int FM_SOC2_DISK_OUT_USED = 31009;
constexpr int FM_SOC2_FILESYSTEM_RUN_ERROR = 31010;
constexpr int FM_SOC2_FILESYSTEM_START_ERROR = 31011;
constexpr int FM_SOC2_SYSTEM_HANDLER_EXCEPTION = 31012;
constexpr int FM_SOC2_SYSTEM_CLOCK_SYNC_ERROR = 31013;
constexpr int FM_SOC2_SYSTEM_CLOCK_SYNC_CHANGE_ERROR = 31014;
constexpr int FM_SOC2_SYSTEM_TIMER_OUT_OF_SYNC = 31015;
constexpr int FM_SOC2_NETWORK_THROUGHPUT_ERROR = 31016;
constexpr int FM_SOC2_PROCESS_COREDUMP_ERROR = 31021;
constexpr int FM_SOC2_THREAD_EXCEPTION_ERROR = 31023;
constexpr int FM_SOC2_DISCONNECT_ERROR = 31027;

//FM_SOC2_OS_XXX    31501-31800

//FM_MCU1_NV_XXX    32001-32500
constexpr int FM_ROS_SOC2_PUB_FAILED = 32101;
constexpr int FM_ROS_SOC2_SUB_FAILED = 32102;
constexpr int FM_ROS_SOC2_INCONSISTENT = 32103;
constexpr int FM_ROS_SOC2_QOS_INCOMPATABLE = 32104;
constexpr int FM_ROS_SOC2_SAMPLE_LOST = 32105;
constexpr int FM_ROS_SOC2_SAMPLE_REJECTED = 32106;
constexpr int FM_ROS_SOC2_PUB_LIVELINESS_CHANGED = 32107;
constexpr int FM_ROS_SOC2_SUB_DOWN = 32108;
constexpr int FM_ROS_SOC2_PUB_DOWN = 32109;
constexpr int FM_ROS_SOC2_PUB_DEADLINE_MISSED = 32110;
constexpr int FM_ROS_SOC2_SUB_DEADLINE_MISSED = 32111;
constexpr int FM_ROS_SOC2_LATENCY_HEIGH = 32112;

//FM_MCU1_PLT_XXX    33001-33500

//FM_MCU2_NV_XXX    34001-34500

//FM_MCU2_PLT_XXX    35001-35500

//FM_CAMERA_LONG_FRONT_DRV_XXX    36001-36060

//FM_CAMERA_LONG_FRONT_DRV_XXX    36061-36100
constexpr int FM_CAMERA_LONG_FRONT_DRV_MISMATCH_MODEL = 36061;
constexpr int FM_CAMERA_LONG_FRONT_DRV_MISMATCH_FIRMWARE = 36062;
constexpr int FM_CAMERA_LONG_FRONT_DRV_SYSTEM_NOT_SYNC = 36063;
constexpr int FM_CAMERA_LONG_FRONT_DRV_SENSOR_NOT_SYNC = 36064;
constexpr int FM_CAMERA_LONG_FRONT_DRV_INSUFFICIENT_FRAME_RATE = 36065;
constexpr int FM_CAMERA_LONG_FRONT_DRV_UNCALIBRATED = 36066;
constexpr int FM_CAMERA_LONG_FRONT_DRV_LOAD_CONFIG_FAIL = 36067;
constexpr int FM_CAMERA_LONG_FRONT_DRV_SEND_ERROR = 36068;
constexpr int FM_CAMERA_LONG_FRONT_DRV_ID_PASS_THROUGH = 36069;

//FM_CAMERA_RANGE_FRONT_DRV_XXX    36101-36160

//FM_CAMERA_RANGE_FRONT_DRV_XXX    36161-36200
constexpr int FM_CAMERA_RANG_FRONT_DRV_MISMATCH_MODEL = 36161;
constexpr int FM_CAMERA_RANG_FRONT_DRV_MISMATCH_FIRMWARE = 36162;
constexpr int FM_CAMERA_RANG_FRONT_DRV_NOT_SYNC = 36163;
constexpr int FM_CAMERA_RANG_FRONT_DRV_SENSOR_NOT_SYNC = 36164;
constexpr int FM_CAMERA_RANG_FRONT_DRV_INSUFFICIENT_FRAME_RATE = 36165;
constexpr int FM_CAMERA_RANG_FRONT_DRV_UNCALIBRATED = 36166;
constexpr int FM_CAMERA_RANG_FRONT_DRV_LOAD_CONFIG_FAIL = 36167;
constexpr int FM_CAMERA_RANG_FRONT_DRV_SEND_ERROR = 36168;
constexpr int FM_CAMERA_RANG_FRONT_DRV_ID_PASS_THROUGH = 36169;

//FM_CAMERA_SIDE_LEFT_FRONT_DRV_XXX    36201-36260

//FM_CAMERA_SIDE_LEFT_FRONT_DRV_XXX    36261-36300
constexpr int FM_CAMERA_SIDE_LEFT_FRONT_DRV_MISMATCH_MODEL = 36261;
constexpr int FM_CAMERA_SIDE_LEFT_FRONT_DRV_MISMATCH_FIRMWARE = 36262;
constexpr int FM_CAMERA_SIDE_LEFT_FRONT_DRV_NOT_SYNC = 36263;
constexpr int FM_CAMERA_SIDE_LEFT_FRONT_DRV_SENSOR_NOT_SYNC = 36264;
constexpr int FM_CAMERA_SIDE_LEFT_FRONT_DRV_INSUFFICIENT_FRAME_RATE = 36265;
constexpr int FM_CAMERA_SIDE_LEFT_FRONT_DRV_UNCALIBRATED = 36266;
constexpr int FM_CAMERA_SIDE_LEFT_FRONT_DRV_LOAD_CONFIG_FAIL = 36267;
constexpr int FM_CAMERA_SIDE_LEFT_FRONT_DRV_SEND_ERROR = 36268;
constexpr int FM_CAMERA_SIDE_LEFT_FRONT_DRV_ID_PASS_THROUGH = 36269;

//FM_CAMERA_SIDE_RIGHT_FRONT_DRV_XXX    36301-36360

//FM_CAMERA_SIDE_RIGHT_FRONT_DRV_XXX    36361-36400
constexpr int FM_CAMERA_SIDE_RIGHT_FRONT_DRV_MISMATCH_MODEL = 36361;
constexpr int FM_CAMERA_SIDE_RIGHT_FRONT_DRV_MISMATCH_FIRMWARE = 36362;
constexpr int FM_CAMERA_SIDE_RIGHT_FRONT_DRV_NOT_SYNC = 36363;
constexpr int FM_CAMERA_SIDE_RIGHT_FRONT_DRV_SENSOR_NOT_SYNC = 36364;
constexpr int FM_CAMERA_SIDE_RIGHT_FRONT_DRV_INSUFFICIENT_FRAME_RATE = 36365;
constexpr int FM_CAMERA_SIDE_RIGHT_FRONT_DRV_UNCALIBRATED = 36366;
constexpr int FM_CAMERA_SIDE_RIGHT_FRONT_DRV_LOAD_CONFIG_FAIL = 36367;
constexpr int FM_CAMERA_SIDE_RIGHT_FRONT_DRV_SEND_ERROR = 36368;
constexpr int FM_CAMERA_SIDE_RIGHT_FRONT_DRV_ID_PASS_THROUGH = 36369;

//FM_CAMERA_SIDE_LEFT_REAR_DRV_XXX    36401-36460

//FM_CAMERA_SIDE_LEFT_REAR_DRV_XXX    36461-36500
constexpr int FM_CAMERA_SIDE_LEFT_REAR_DRV_MISMATCH_MODEL = 36461;
constexpr int FM_CAMERA_SIDE_LEFT_REAR_DRV_MISMATCH_FIRMWARE = 36462;
constexpr int FM_CAMERA_SIDE_LEFT_REAR_DRV_NOT_SYNC = 36463;
constexpr int FM_CAMERA_SIDE_LEFT_REAR_DRV_SENSOR_NOT_SYNC = 36464;
constexpr int FM_CAMERA_SIDE_LEFT_REAR_DRV_INSUFFICIENT_FRAME_RATE = 36465;
constexpr int FM_CAMERA_SIDE_LEFT_REAR_DRV_UNCALIBRATED = 36466;
constexpr int FM_CAMERA_SIDE_LEFT_REAR_DRV_LOAD_CONFIG_FAIL = 36467;
constexpr int FM_CAMERA_SIDE_LEFT_REAR_DRV_SEND_ERROR = 36468;
constexpr int FM_CAMERA_SIDE_LEFT_REAR_DRV_ID_PASS_THROUGH = 36469;

//FM_CAMERA_SIDE_RIGHT_REAR_DRV_XXX    36501-36560

//FM_CAMERA_SIDE_RIGHT_REAR_DRV_XXX    36561-36600
constexpr int FM_CAMERA_SIDE_RIGHT_REAR_DRV_MISMATCH_MODEL = 36561;
constexpr int FM_CAMERA_SIDE_RIGHT_REAR_DRV_MISMATCH_FIRMWARE = 36562;
constexpr int FM_CAMERA_SIDE_RIGHT_REAR_DRV_NOT_SYNC = 36563;
constexpr int FM_BASE_CAMERA_DVR_UNCALIBRATED = 36564;
constexpr int FM_CAMERA_SIDE_RIGHT_REAR_DRV_INSUFFICIENT_FRAME_RATE = 36565;
constexpr int FM_CAMERA_SIDE_RIGHT_REAR_DRV_UNCALIBRATED = 36566;
constexpr int FM_CAMERA_SIDE_RIGHT_REAR_DRV_LOAD_CONFIG_FAIL = 36567;
constexpr int FM_CAMERA_SIDE_RIGHT_REAR_DRV_SEND_ERROR = 36568;
constexpr int FM_CAMERA_SIDE_RIGHT_REAR_DRV_ID_PASS_THROUGH = 36569;

//FM_CAMERA_REAR_DRV_XXX    36601-36660

//FM_CAMERA_REAR_DRV_XXX    36661-36700
constexpr int FM_CAMERA_REAR_DRV_MISMATCH_MODEL = 36661;
constexpr int FM_CAMERA_REAR_DRV_MISMATCH_FIRMWARE = 36662;
constexpr int FM_CAMERA_REAR_DRV_NOT_SYNC = 36663;
constexpr int FM_CAMERA_REAR_DRV_SENSOR_NOT_SYNC = 36664;
constexpr int FM_CAMERA_REAR_DRV_INSUFFICIENT_FRAME_RATE = 36665;
constexpr int FM_CAMERA_REAR_DRV_UNCALIBRATED = 36666;
constexpr int FM_CAMERA_REAR_DRV_LOAD_CONFIG_FAIL = 36667;
constexpr int FM_CAMERA_REAR_DRV_SEND_ERROR = 36668;
constexpr int FM_CAMERA_REAR_DRV_ID_PASS_THROUGH = 36669;

//FM_CAMERA_SUR_LEFT_FRONT_DRV_XXX    36701-36760

//FM_CAMERA_SUR_LEFT_FRONT_DRV_XXX    36761-36800
constexpr int FM_CAMERA_SUR_FRONT_DRV_MISMATCH_MODEL = 36761;
constexpr int FM_CAMERA_SUR_FRONT_DRV_MISMATCH_FIRMWARE = 36762;
constexpr int FM_CAMERA_SUR_FRONT_DRV_NOT_SYNC = 36763;
constexpr int FM_CAMERA_SUR_FRONT_DRV_SENSOR_NOT_SYNC = 36764;
constexpr int FM_CAMERA_SUR_FRONT_DRV_INSUFFICIENT_FRAME_RATE = 36765;
constexpr int FM_CAMERA_SUR_FRONT_DRV_UNCALIBRATED = 36766;
constexpr int FM_CAMERA_SUR_FRONT_DRV_LOAD_CONFIG_FAIL = 36767;
constexpr int FM_CAMERA_SUR_FRONT_DRV_SEND_ERROR = 36768;
constexpr int FM_CAMERA_SUR_FRONT_DRV_ID_PASS_THROUGH = 36769;

//FM_CAMERA_SUR_RIGHT_FRONT_DRV_XXX    36801-36860

//FM_CAMERA_SUR_RIGHT_FRONT_DRV_XXX    36861-36900
constexpr int FM_CAMERA_SUR_RIGHT_DRV_MISMATCH_MODEL = 36861;
constexpr int FM_CAMERA_SUR_RIGHT_DRV_MISMATCH_FIRMWARE = 36862;
constexpr int FM_CAMERA_SUR_RIGHT_DRV_NOT_SYNC = 36863;
constexpr int FM_CAMERA_SUR_RIGHT_DRV_SENSOR_NOT_SYNC = 36864;
constexpr int FM_CAMERA_SUR_RIGHT_DRV_INSUFFICIENT_FRAME_RATE = 36865;
constexpr int FM_CAMERA_SUR_RIGHT_DRV_UNCALIBRATED = 36866;
constexpr int FM_CAMERA_SUR_RIGHT_DRV_LOAD_CONFIG_FAIL = 36867;
constexpr int FM_CAMERA_SUR_RIGHT_DRV_SEND_ERROR = 36868;
constexpr int FM_CAMERA_SUR_RIGHT_DRV_ID_PASS_THROUGH = 36869;

//FM_CAMERA_SUR_LEFT_REAR_DRV_XXX    36901-36960

//FM_CAMERA_SUR_LEFT_REAR_DRV_XXX    36961-37000
constexpr int FM_CAMERA_SUR_LEFT_DRV_MISMATCH_MODEL = 36961;
constexpr int FM_CAMERA_SUR_LEFT_DRV_MISMATCH_FIRMWARE = 36962;
constexpr int FM_CAMERA_SUR_LEFT_DRV_NOT_SYNC = 36963;
constexpr int FM_CAMERA_SUR_LEFT_DRV_SENSOR_NOT_SYNC = 36964;
constexpr int FM_CAMERA_SUR_LEFT_DRV_INSUFFICIENT_FRAME_RATE = 36965;
constexpr int FM_CAMERA_SUR_LEFT_DRV_UNCALIBRATED = 36966;
constexpr int FM_CAMERA_SUR_LEFT_DRV_LOAD_CONFIG_FAIL = 36967;
constexpr int FM_CAMERA_SUR_LEFT_DRV_SEND_ERROR = 36968;
constexpr int FM_CAMERA_SUR_LEFT_DRV_ID_PASS_THROUGH = 36969;

//FM_CAMERA_SUR_RIGHT_REAR_DRV_XXX    37001-37060

//FM_CAMERA_SUR_RIGHT_REAR_DRV_XXX    37061-37100
constexpr int FM_CAMERA_SUR_REAR_DRV_MISMATCH_MODEL = 37061;
constexpr int FM_CAMERA_SUR_REAR_DRV_MISMATCH_FIRMWARE = 37062;
constexpr int FM_CAMERA_SUR_REAR_DRV_NOT_SYNC = 37063;
constexpr int FM_CAMERA_SUR_REAR_DRV_SENSOR_NOT_SYNC = 37064;
constexpr int FM_CAMERA_SUR_REAR_DRV_INSUFFICIENT_FRAME_RATE = 37065;
constexpr int FM_CAMERA_SUR_REAR_DRV_UNCALIBRATED = 37066;
constexpr int FM_CAMERA_SUR_REAR_DRV_LOAD_CONFIG_FAIL = 37067;
constexpr int FM_CAMERA_SUR_REAR_DRV_SEND_ERROR = 37068;
constexpr int FM_CAMERA_SUR_REAR_DRV_ID_PASS_THROUGH = 37069;

//FM_SMART_CAMERA_DRV_XXX    37101-37200
constexpr int FM_SMART_CAMERA_DRV_NOT_SYNC = 37101;
constexpr int FM_SMART_CAMERA_DRV_RECEIVE_TIMEOUT = 37102;
constexpr int FM_SMART_CAMERA_DRV_FRAME_DROPPED = 37103;
constexpr int FM_SMART_CAMERA_DRV_PERIODIC_ANOMALY = 37104;
constexpr int FM_SMART_CAMERA_DRV_SEND_SOC_ERROR = 37105;
constexpr int FM_SMART_CAMERA_DRV_ID_PASS_THROUGH = 37106;
constexpr int FM_SMART_CAMERA_DRV_E2E_CHECK_FAIL = 37107;

//FM_LIDAR_FRONT_DRV_XXX    37201-37300
constexpr int FM_LIDAR_FRONT_DRV_CONNECT_FAIL = 37201;
constexpr int FM_LIDAR_FRONT_DRV_MISMATCH_MODEL = 37202;
constexpr int FM_LIDAR_FRONT_DRV_MISMATCH_FIRMWARE = 37203;
constexpr int FM_LIDAR_FRONT_DRV_E2E_CHECK_FAIL = 37204;
constexpr int FM_LIDAR_FRONT_DRV_RECV_TIMEOUT = 37205;
constexpr int FM_LIDAR_FRONT_DRV_NOT_SYNC = 37206;
constexpr int FM_LIDAR_FRONT_DRV_UNCALIBRATED = 37207;
constexpr int FM_LIDAR_FRONT_DRV_LOAD_CONFIG_FAIL = 37208;
constexpr int FM_LIDAR_FRONT_DRV_ID_PASS_THROUGH = 37209;

//FM_LIDAR_SIDE_LEFT_DRV_XXX    37301-37400
constexpr int FM_LIDAR_SIDE_LEFT_DRV_CONNECT_FAIL = 37301;
constexpr int FM_LIDAR_SIDE_LEFT_DRV_MISMATCH_MODEL = 37302;
constexpr int FM_LIDAR_SIDE_LEFT_DRV_MISMATCH_FIRMWARE = 37303;
constexpr int FM_LIDAR_SIDE_LEFT_DRV_E2E_CHECK_FAIL = 37304;
constexpr int FM_LIDAR_SIDE_LEFT_DRV_RECV_TIMEOUT = 37305;
constexpr int FM_LIDAR_SIDE_LEFT_DRV_NOT_SYNC = 37306;
constexpr int FM_LIDAR_SIDE_LEFT_DRV_UNCALIBRATED = 37307;
constexpr int FM_LIDAR_SIDE_LEFT_DRV_LOAD_CONFIG_FAIL = 37308;
constexpr int FM_LIDAR_SIDE_LEFT_DRV_ID_PASS_THROUGH = 37309;

//FM_LIDAR_SIDE_RIGHT_DRV_XXX    37401-37500
constexpr int FM_LIDAR_SIDE_RIGHT_DRV_CONNECT_FAIL = 37401;
constexpr int FM_LIDAR_SIDE_RIGHT_DRV_MISMATCH_MODEL = 37402;
constexpr int FM_LIDAR_SIDE_RIGHT_DRV_MISMATCH_FIRMWARE = 37403;
constexpr int FM_LIDAR_SIDE_RIGHT_DRV_E2E_CHECK_FAIL = 37404;
constexpr int FM_LIDAR_SIDE_RIGHT_DRV_RECV_TIMEOUT = 37405;
constexpr int FM_LIDAR_SIDE_RIGHT_DRV_NOT_SYNC = 37406;
constexpr int FM_LIDAR_SIDE_RIGHT_DRV_UNCALIBRATED = 37407;
constexpr int FM_LIDAR_SIDE_RIGHT_DRV_LOAD_CONFIG_FAIL = 37408;
constexpr int FM_LIDAR_SIDE_RIGHT_DRV_ID_PASS_THROUGH = 37409;

//FM_RADAR_FRONT_DRV_XXX    37501-37600
constexpr int FM_RADAR_FRONT_DRV_SEND_ERROR = 37501;
constexpr int FM_RADAR_FRONT_DRV_NOT_SYNC = 37502;
constexpr int FM_RADAR_FRONT_DRV_ID_PASS_THROUGH = 37503;
constexpr int FM_RADAR_FRONT_DRV_FRAME_DROPPED = 37504;
constexpr int FM_RADAR_FRONT_DRV_PERIODIC_ANOMALY = 37505;
constexpr int FM_RADAR_FRONT_DRV_MISMATCH_FIRMWARE = 37506;
constexpr int FM_RADAR_FRONT_DRV_RECV_TIMEOUT = 37507;
constexpr int FM_RADAR_FRONT_DRV_E2E_CHECK_FAIL = 37508;

//FM_RADAR_SIDE_LEFT_FRONT_DRV_XXX    37601-37700
constexpr int FM_RADAR_SIDE_LEFT_FRONT_DRV_SEND_ERROR = 37601;
constexpr int FM_RADAR_SIDE_LEFT_FRONT_DRV_NOT_SYNC = 37602;
constexpr int FM_RADAR_SIDE_LEFT_FRONT_DRV_ID_PASS_THROUGH = 37603;
constexpr int FM_RADAR_SIDE_LEFT_FRONT_DRV_FRAME_DROPPED = 37604;
constexpr int FM_RADAR_SIDE_LEFT_FRONT_DRV_PERIODIC_ANOMALY = 37605;
constexpr int FM_RADAR_SIDE_LEFT_FRONT_DRV_MISMATCH_FIRMWARE = 37606;
constexpr int FM_RADAR_SIDE_LEFT_FRONT_DRV_RECV_TIMEOUT = 37607;
constexpr int FM_RADAR_SIDE_LEFT_FRONT_DRV_E2E_CHECK_FAIL = 37608;

//FM_RADAR_SIDE_RIGHT_FRONT_DRV_XXX    37701-37800
constexpr int FM_RADAR_SIDE_RIGHT_FRONT_DRV_SEND_ERROR = 37701;
constexpr int FM_RADAR_SIDE_RIGHT_FRONT_DRV_NOT_SYNC = 37702;
constexpr int FM_RADAR_SIDE_RIGHT_FRONT_DRV_ID_PASS_THROUGH = 37703;
constexpr int FM_RADAR_SIDE_RIGHT_FRONT_DRV_FRAME_DROPPED = 37704;
constexpr int FM_RADAR_SIDE_RIGHT_FRONT_DRV_PERIODIC_ANOMALY = 37705;
constexpr int FM_RADAR_SIDE_RIGHT_FRONT_DRV_MISMATCH_FIRMWARE = 37706;
constexpr int FM_RADAR_SIDE_RIGHT_FRONT_DRV_RECV_TIMEOUT = 37707;
constexpr int FM_RADAR_SIDE_RIGHT_FRONT_DRV_E2E_CHECK_FAIL = 37708;

//FM_RADAR_SIDE_LEFT_REAR_DRV_XXX    37801-37900
constexpr int FM_RADAR_SIDE_LEFT_REAR_DRV_SEND_ERROR = 37801;
constexpr int FM_RADAR_SIDE_LEFT_REAR_DRV_NOT_SYNC = 37802;
constexpr int FM_RADAR_SIDE_LEFT_REAR_DRV_ID_PASS_THROUGH = 37803;
constexpr int FM_RADAR_SIDE_LEFT_REAR_DRV_FRAME_DROPPED = 37804;
constexpr int FM_RADAR_SIDE_LEFT_REAR_DRV_PERIODIC_ANOMALY = 37805;
constexpr int FM_RADAR_SIDE_LEFT_REAR_DRV_MISMATCH_FIRMWARE = 37806;
constexpr int FM_RADAR_SIDE_LEFT_REAR_DRV_RECV_TIMEOUT = 37807;
constexpr int FM_RADAR_SIDE_LEFT_REAR_DRV_E2E_CHECK_FAIL = 37808;

//FM_RADAR_SIDE_RIGHT_REAR_DRV_XXX    37901-38000
constexpr int FM_RADAR_SIDE_RIGHT_REAR_DRV_SEND_ERROR = 37901;
constexpr int FM_RADAR_SIDE_RIGHT_REAR_DRV_NOT_SYNC = 37902;
constexpr int FM_RADAR_SIDE_RIGHT_REAR_DRV_ID_PASS_THROUGH = 37903;
constexpr int FM_RADAR_SIDE_RIGHT_REAR_DRV_FRAME_DROPPED = 37904;
constexpr int FM_RADAR_SIDE_RIGHT_REAR_DRV_PERIODIC_ANOMALY = 37905;
constexpr int FM_RADAR_SIDE_RIGHT_REAR_DRV_MISMATCH_FIRMWARE = 37906;
constexpr int FM_RADAR_SIDE_RIGHT_REAR_DRV_RECV_TIMEOUT = 37907;
constexpr int FM_RADAR_SIDE_RIGHT_REAR_DRV_E2E_CHECK_FAIL = 37908;

//FM_USS_FRONT_DRV_XXX    38001-38100

//FM_USS_SIDE_LEFT_FRONT_DRV_XXX    38101-38200

//FM_USS_SIDE_RIGHT_FRONT_DRV_XXX    38201-38300

//FM_USS_SUR_LEFT_REAR_DRV_XXX    38301-38400

//FM_USS_SUR_RIGHT_REAR_DRV_XXX    38401-38500

//FM_USS_REAR_DRV_XXX    38501-38600

//FM_PDCM_DRV_XXX    38601-38700
constexpr int FM_PDCM_DRV_NOT_SYNC = 38601;
constexpr int FM_PDCM_DRV_POINT_FRAME_DROPPED = 38602;
constexpr int FM_PDCM_DRV_PS_FRAME_DROPPED = 38603;
constexpr int FM_PDCM_DRV_WAVE_FRAME_DROPPED = 38604;
constexpr int FM_PDCM_DRV_PERIODIC_ANOMALY = 38605;
constexpr int FM_PDCM_DRV_SEND_ERROR = 38606;
constexpr int FM_PDCM_DRV_ID_PASS_THROUGH = 38607;

//FM_PERCP_ENVPERCP_XXX    40001-40500
constexpr int FM_PERCP_ENVPERCP_RELATIVE_MSG_GET_TIMEOUT = 40001;
constexpr int FM_PERCP_ENVPERCP_RELATIVE_MSG_DELAY_ABNORMAL = 40002;
constexpr int FM_PERCP_ENVPERCP_CAMERA_CALIB_GET_TIMEOUT = 40003;
constexpr int FM_PERCP_ENVPERCP_J3_MSG_GET_TIMEOUT = 40004;
constexpr int FM_PERCP_ENVPERCP_J3_MSG_DELAY_ABNORMAL = 40005;
constexpr int FM_PERCP_ENVPERCP_FRONT_WIDE_IMAGE_GET_TIMEOUT = 40006;
constexpr int FM_PERCP_ENVPERCP_FRONT_WIDE_IMAGE_DELAY_ABNORMAL = 40007;
constexpr int FM_PERCP_ENVPERCP_TRAFFICLANE_PROCESS_TIMEOUT = 40008;
constexpr int FM_PERCP_ENVPERCP_TRAFFICLANE_CONFIG_FILE_NOT_EXIST = 40009;
constexpr int FM_PERCP_ENVPERCP_TRAFFICLANE_MODEL_FILE_NOT_EXIST = 40010;
constexpr int FM_PERCP_ENVPERCP_FRONT_WIDE_CAMERA_SHELTER = 40011;

//FM_PERCP_OBJPERCP_XXX    41001-41500
constexpr int FM_PERCP_OBJPERCP_FUSION_LOCALIZATION_TIME_DIFF_ABNORMAL = 41001;
constexpr int FM_PERCP_OBJPERCP_FUSION_RADAR_PERCP_TIME_DIFF_ABNORMAL = 41002;
constexpr int FM_PERCP_OBJPERCP_FUSION_LIDAR_PERCP_TIME_DIFF_ABNORMAL = 41003;
constexpr int FM_PERCP_OBJPERCP_FUSION_VISION_PERCP_TIME_DIFF_ABNORMAL = 41004;
constexpr int FM_PERCP_OBJPERCP_FUSION_SMART_CAMERA_PERCP_TIME_DIFF_ABNORMAL = 41005;
constexpr int FM_PERCP_OBJPERCP_FUSION_SMART_CAMERA_CALIB_TIME_DIFF_ABNORMAL = 41006;
constexpr int FM_PERCP_OBJPERCP_FUSION_ZEEKR_CALIB_TIME_DIFF_ABNORMAL = 41007;
constexpr int FM_PERCP_OBJPERCP_FUSION_LOCALIZATION_TIMEOUT = 41008;
constexpr int FM_PERCP_OBJPERCP_FUSION_RADAR_PERCP_TIMEOUT = 41009;
constexpr int FM_PERCP_OBJPERCP_FUSION_LIDAR_PERCP_TIMEOUT = 41010;
constexpr int FM_PERCP_OBJPERCP_FUSION_VISION_PERCP_TIMEOUT = 41011;
constexpr int FM_PERCP_OBJPERCP_FUSION_SMART_CAMERA_PERCP_TIMEOUT = 41012;
constexpr int FM_PERCP_OBJPERCP_FUSION_SMART_CAMERA_CALIB_TIMEOUT = 41013;
constexpr int FM_PERCP_OBJPERCP_FUSION_ZEEKR_CALIB_TIMEOUT = 41014;
constexpr int FM_PERCP_OBJPERCP_FUSION_LOCALIZATION_RECEVIE_LATENCY_ABNORMAL = 41015;
constexpr int FM_PERCP_OBJPERCP_FUSION_RADAR_PERCP_RECEVIE_LATENCY_ABNORMAL = 41016;
constexpr int FM_PERCP_OBJPERCP_FUSION_LIDAR_PERCP_RECEVIE_LATENCY_ABNORMAL = 41017;
constexpr int FM_PERCP_OBJPERCP_FUSION_VISION_PERCP_RECEVIE_LATENCY_ABNORMAL = 41018;
constexpr int FM_PERCP_OBJPERCP_FUSION_SAMRT_CAMERA_PERCP_RECEIVE_LATENCY_ABNORMAL = 41019;
constexpr int FM_PERCP_OBJPERCP_FUSION_SMART_CAMERA_CALIB_RECEIVE_LATENCY_ABNORMAL = 41020;
constexpr int FM_PERCP_OBJPERCP_FUSION_ZEEKR_CALIB_RECEIVE_LATENCY_ABNORMAL = 41021;
constexpr int FM_PERCP_OBJPERCP_LIDAR_LOCALIZATION_TIME_DIFF_ABNORMAL = 41022;
constexpr int FM_PERCP_OBJPERCP_LIDAR_STITCH_POINT_TIME_DIFF_ABNORMAL = 41023;
constexpr int FM_PERCP_OBJPERCP_LIDAR_LOCALIZATION_TIMEOUT = 41024;
constexpr int FM_PERCP_OBJPERCP_LIDAR_STITCH_POINT_TIMEOUT = 41025;
constexpr int FM_PERCP_OBJPERCP_LIDAR_LOCALIZATION_RECEVIE_LATENCY_ABNORMAL = 41026;
constexpr int FM_PERCP_OBJPERCP_LIDAR_STITCH_POINT_RECEVIE_LATENCY_ABNORMAL = 41027;
constexpr int FM_PERCP_OBJPERCP_RADAR_LOCALIZATION_TIME_DIFF_ABNORMAL = 41028;
constexpr int FM_PERCP_OBJPERCP_RADAR_LOCALIZATION_TIMEOUT = 41029;
constexpr int FM_PERCP_OBJPERCP_RADAR_LOCALIZATION_RECEVIE_LATENCY_ABNORMAL = 41030;
constexpr int FM_PERCP_OBJPERCP_RADAR_ZEEKR_CALIB_TIME_DIFF_ABNORMAL = 41031;
constexpr int FM_PERCP_OBJPERCP_RADAR_ZEEKR_CALIB_TIMEOUT = 41032;
constexpr int FM_PERCP_OBJPERCP_RADAR_ZEEKR_CALIB_RECEVIE_LATENCY_ABNORMAL = 41033;
constexpr int FM_PERCP_OBJPERCP_RADAR_FRONT_OBJECT_TIME_DIFF_ABNORMAL = 41034;
constexpr int FM_PERCP_OBJPERCP_RADAR_FRONT_OBJECT_TIMEOUT = 41035;
constexpr int FM_PERCP_OBJPERCP_RADAR_FRONT_OBJECT_RECEVIE_LATENCY_ABNORMAL = 41036;
constexpr int FM_PERCP_OBJPERCP_RADAR_FRONT_CLUSTER_TIME_DIFF_ABNORMAL = 41037;
constexpr int FM_PERCP_OBJPERCP_RADAR_FRONT_CLUSTER_TIMEOUT = 41038;
constexpr int FM_PERCP_OBJPERCP_RADAR_FRONT_CLUSTER_RECEVIE_LATENCY_ABNORMAL = 41039;
constexpr int FM_PERCP_OBJPERCP_RADAR_LEFT_FRONT_OBJECT_TIME_DIFF_ABNORMAL = 41040;
constexpr int FM_PERCP_OBJPERCP_RADAR_LEFT_FRONT_OBJECT_TIMEOUT = 41041;
constexpr int FM_PERCP_OBJPERCP_RADAR_LEFT_FRONT_OBJECT_RECEVIE_LATENCY_ABNORMAL = 41042;
constexpr int FM_PERCP_OBJPERCP_RADAR_LEFT_FRONT_CLUSTER_TIME_DIFF_ABNORMAL = 41043;
constexpr int FM_PERCP_OBJPERCP_RADAR_LEFT_FRONT_CLUSTER_TIMEOUT = 41044;
constexpr int FM_PERCP_OBJPERCP_RADAR_LEFT_FRONT_CLUSTER_RECEVIE_LATENCY_ABNORMAL = 41045;
constexpr int FM_PERCP_OBJPERCP_RADAR_LEFT_REAR_OBJECT_TIME_DIFF_ABNORMAL = 41046;
constexpr int FM_PERCP_OBJPERCP_RADAR_LEFT_REAR_OBJECT_TIMEOUT = 41047;
constexpr int FM_PERCP_OBJPERCP_RADAR_LEFT_REAR_OBJECT_RECEVIE_LATENCY_ABNORMAL = 41048;
constexpr int FM_PERCP_OBJPERCP_RADAR_LEFT_REAR_CLUSTER_TIME_DIFF_ABNORMAL = 41049;
constexpr int FM_PERCP_OBJPERCP_RADAR_LEFT_REAR_CLUSTER_TIMEOUT = 41050;
constexpr int FM_PERCP_OBJPERCP_RADAR_LEFT_REAR_CLUSTER_RECEVIE_LATENCY_ABNORMAL = 41051;
constexpr int FM_PERCP_OBJPERCP_RADAR_RIGHT_FRONT_OBJECT_TIME_DIFF_ABNORMAL = 41052;
constexpr int FM_PERCP_OBJPERCP_RADAR_RIGHT_FRONT_OBJECT_TIMEOUT = 41053;
constexpr int FM_PERCP_OBJPERCP_RADAR_RIGHT_FRONT_OBJECT_RECEVIE_LATENCY_ABNORMAL = 41054;
constexpr int FM_PERCP_OBJPERCP_RADAR_RIGHT_FRONT_CLUSTER_TIME_DIFF_ABNORMAL = 41055;
constexpr int FM_PERCP_OBJPERCP_RADAR_RIGHT_FRONT_CLUSTER_TIMEOUT = 41056;
constexpr int FM_PERCP_OBJPERCP_RADAR_RIGHT_FRONT_CLUSTER_RECEVIE_LATENCY_ABNORMAL = 41057;
constexpr int FM_PERCP_OBJPERCP_RADAR_RIGHT_REAR_OBJECT_TIME_DIFF_ABNORMAL = 41058;
constexpr int FM_PERCP_OBJPERCP_RADAR_RIGHT_REAR_OBJECT_TIMEOUT = 41059;
constexpr int FM_PERCP_OBJPERCP_RADAR_RIGHT_REAR_OBJECT_RECEVIE_LATENCY_ABNORMAL = 41060;
constexpr int FM_PERCP_OBJPERCP_RADAR_RIGHT_REAR_CLUSTER_TIME_DIFF_ABNORMAL = 41061;
constexpr int FM_PERCP_OBJPERCP_RADAR_RIGHT_REAR_CLUSTER_TIMEOUT = 41062;
constexpr int FM_PERCP_OBJPERCP_RADAR_RIGHT_REAR_CLUSTER_RECEVIE_LATENCY_ABNORMAL = 41063;
constexpr int FM_PERCP_OBJPERCP_VISION_LOCALIZATION_TIME_DIFF_ABNORMAL = 41064;
constexpr int FM_PERCP_OBJPERCP_VISION_LOCALIZATION_TIMEOUT = 41065;
constexpr int FM_PERCP_OBJPERCP_VISION_LOCALIZATION_RECEVIE_LATENCY_ABNORMAL = 41066;
constexpr int FM_PERCP_OBJPERCP_VISION_ZEEKR_CALIB_TIME_DIFF_ABNORMAL = 41067;
constexpr int FM_PERCP_OBJPERCP_VISION_ZEEKR_CALIB_TIMEOUT = 41068;
constexpr int FM_PERCP_OBJPERCP_VISION_ZEEKR_CALIB_RECEVIE_LATENCY_ABNORMAL = 41069;
constexpr int FM_PERCP_OBJPERCP_VISION_FRONT_WIDE_IMAGE_TIME_DIFF_ABNORMAL = 41070;
constexpr int FM_PERCP_OBJPERCP_VISION_FRONT_WIDE_IMAGE_TIMEOUT = 41071;
constexpr int FM_PERCP_OBJPERCP_VISION_FRONT_WIDE_IMAGE_RECEVIE_LATENCY_ABNORMAL = 41072;
constexpr int FM_PERCP_OBJPERCP_VISION_FRONT_LONG_IMAGE_TIME_DIFF_ABNORMAL = 41073;
constexpr int FM_PERCP_OBJPERCP_VISION_FRONT_LONG_IMAGE_TIMEOUT = 41074;
constexpr int FM_PERCP_OBJPERCP_VISION_FRONT_LONG_IMAGE_RECEVIE_LATENCY_ABNORMAL = 41075;
constexpr int FM_PERCP_OBJPERCP_VISION_LEFT_FRONT_IMAGE_TIME_DIFF_ABNORMAL = 41076;
constexpr int FM_PERCP_OBJPERCP_VISION_LEFT_FRONT_IMAGE_TIMEOUT = 41077;
constexpr int FM_PERCP_OBJPERCP_VISION_LEFT_FRONT_IMAGE_RECEVIE_LATENCY_ABNORMAL = 41078;
constexpr int FM_PERCP_OBJPERCP_VISION_LEFT_REAR_IMAGE_TIME_DIFF_ABNORMAL = 41079;
constexpr int FM_PERCP_OBJPERCP_VISION_LEFT_REAR_IMAGE_TIMEOUT = 41080;
constexpr int FM_PERCP_OBJPERCP_VISION_LEFT_REAR_IMAGE_RECEVIE_LATENCY_ABNORMAL = 41081;
constexpr int FM_PERCP_OBJPERCP_VISION_RIGHT_FRONT_IMAGE_TIME_DIFF_ABNORMAL = 41082;
constexpr int FM_PERCP_OBJPERCP_VISION_RIGHT_FRONT_IMAGE_TIMEOUT = 41083;
constexpr int FM_PERCP_OBJPERCP_VISION_RIGHT_FRONT_IMAGE_RECEVIE_LATENCY_ABNORMAL = 41084;
constexpr int FM_PERCP_OBJPERCP_VISION_RIGHT_REAR_IMAGE_TIME_DIFF_ABNORMAL = 41085;
constexpr int FM_PERCP_OBJPERCP_VISION_RIGHT_REAR_IMAGE_TIMEOUT = 41086;
constexpr int FM_PERCP_OBJPERCP_VISION_RIGHT_REAR_IMAGE_RECEVIE_LATENCY_ABNORMAL = 41087;
constexpr int FM_PERCP_OBJPERCP_VISION_REAR_IMAGE_TIME_DIFF_ABNORMAL = 41088;
constexpr int FM_PERCP_OBJPERCP_VISION_REAR_IMAGE_TIMEOUT = 41089;
constexpr int FM_PERCP_OBJPERCP_VISION_REAR_IMAGE_RECEVIE_LATENCY_ABNORMAL = 41090;

//FM_PERCP_PARKPERCP_XXX    42001-42500
constexpr int FM_PERCP_PARKPERCP_FRONT_SURROUND_IMAGE_GET_TIMEOUT_IPMNN = 42001;
constexpr int FM_PERCP_PARKPERCP_FRONT_SURROUND_IMAGE_PROCESS_TIMEDFF_IPMNN = 42002;
constexpr int FM_PERCP_PARKPERCP_FRONT_SURROUND_IMAGE_PROCESS_TIMELATENCY_IPMNN = 42003;
constexpr int FM_PERCP_PARKPERCP_REAR_SURROUND_IMAGE_GET_TIMEOUT_IPMNN = 42005;
constexpr int FM_PERCP_PARKPERCP_REAR_SURROUND_IMAGE_PROCESS_TIMEDFF_IPMNN = 42006;
constexpr int FM_PERCP_PARKPERCP_REAR_SURROUND_IMAGE_PROCESS_TIMELATENCY_IPMNN = 42007;
constexpr int FM_PERCP_PARKPERCP_LEFT_SURROUND_IMAGE_GET_TIMEOUT_IPMNN = 42009;
constexpr int FM_PERCP_PARKPERCP_LEFT_SURROUND_IMAGE_PROCESS_TIMEDFF_IPMNN = 42010;
constexpr int FM_PERCP_PARKPERCP_LEFT_SURROUND_IMAGE_PROCESS_TIMELATENCY_IPMNN = 42011;
constexpr int FM_PERCP_PARKPERCP_RIGHT_SURROUND_IMAGE_GET_TIMEOUT_IPMNN = 42013;
constexpr int FM_PERCP_PARKPERCP_RIGHT_SURROUND_IMAGE_PROCESS_TIMEDFF_IPMNN = 42014;
constexpr int FM_PERCP_PARKPERCP_RIGHT_SURROUND_IMAGE_PROCESS_TIMELATENCY_IPMNN = 42015;
constexpr int FM_PERCP_PARKPERCP_CALIB_INFO_GET_TIMEOUT_IPMNN = 42017;
constexpr int FM_PERCP_PARKPERCP_GENRATE_LUT_FAIL_IPMNN = 42018;
constexpr int FM_PERCP_PARKPERCP_FSM_STATE_GET_TIMEOUT_IPMNN = 42019;
constexpr int FM_PERCP_PARKPERCP_FSM_STATE_GET_TIMEDIFF_IPMNN = 42020;
constexpr int FM_PERCP_PARKPERCP_FSM_STATE_GET_TIMELATENCY_IPMNN = 42021;
constexpr int FM_PERCP_PARKPERCP_NO_PARKING_FSM_STATE = 42022;
constexpr int FM_PERCP_PARKPERCP_CONFIG_LOAD_FAIL_IPMNN = 42023;
constexpr int FM_PERCP_PARKPERCP_VISION_SLOT_GET_TIMEOUT_PARKINGSLOT = 42024;
constexpr int FM_PERCP_PARKPERCP_VISION_SLOT_GET_TIMEDIFF_PARKINGSLOT = 42025;
constexpr int FM_PERCP_PARKPERCP_VISION_SLOT_GET_TIMELATENCY_PARKINGSLOT = 42026;
constexpr int FM_PERCP_PARKPERCP_CALIB_INFO_GET_TIMEOUT_PARKINGSLOT = 42027;
constexpr int FM_PERCP_PARKPERCP_GENRATE_LUT_FAIL_PARKINGSLOT = 42028;
constexpr int FM_PERCP_PARKPERCP_RELATIVE_LOC_INFO_GET_TIMEOUT_PARKINGSLOT = 42029;
constexpr int FM_PERCP_PARKPERCP_RELATIVE_LOC_INFO_GET_TIMEDIFF_PARKINGSLOT = 42030;
constexpr int FM_PERCP_PARKPERCP_RELATIVE_LOC_INFO_PROCESS_TIMEOUT_PARKINGSLOT = 42031;
constexpr int FM_PERCP_PARKPERCP_CALIB_INFO_GET_TIMEDIFF_IPMNN = 42118;
constexpr int FM_PERCP_PARKPERCP_CALIB_INFO_PROCESS_TIMEOUT_IPMNN = 42119;
constexpr int FM_PERCP_PARKPERCP_CALIB_INFO_GET_TIMEDIFF_PARKINGSLOT = 42228;
constexpr int FM_PERCP_PARKPERCP_CALIB_INFO_PROCESS_TIMEOUT_PARKINGSLOT = 42229;
constexpr int FM_PERCP_PARKPERCP_FSM_STATE_GET_TIMEOUT_PARKINGSLOT = 42232;
constexpr int FM_PERCP_PARKPERCP_FSM_STATE_GET_TIMEDIFF_PARKINGSLOT = 42233;
constexpr int FM_PERCP_PARKPERCP_FSM_STATE_GET_TIMELATENCY_PARKINGSLOT = 42234;
constexpr int FM_PERCP_PARKPERCP_CONFIG_LOAD_FAIL_PARKINGSLOT = 42236;

//FM_LOC_LOC_XXX    43001-43500
constexpr int FM_LOC_LOC_RELATIVE_IMU_TIMEOUT = 43001;
constexpr int FM_LOC_LOC_RELATIVE_IMU_ABNORMAL = 43002;
constexpr int FM_LOC_LOC_RELATIVE_CHASSIS_REPORT_TIMEOUT = 43003;
constexpr int FM_LOC_LOC_RELATIVE_CHASSIS_REPORT_ABNORMAL = 43004;
constexpr int FM_LOC_LOC_RELATIVE_GET_CALIBPARAM_FAILED = 43005;
constexpr int FM_LOC_LOC_RELATIVE_ABNORMAL_STATE = 43006;
constexpr int FM_LOC_LOC_RELATIVE_NO_SMOOTH = 43007;
constexpr int FM_LOC_FUSON_IMU_TIMEOUT = 43101;
constexpr int FM_LOC_FUSON_IMU_ABNORMAL = 43102;
constexpr int FM_LOC_FUSON_GNSS_TIMEOUT = 43103;
constexpr int FM_LOC_FUSON_GNSS_ABNORMAL = 43104;
constexpr int FM_LOC_FUSON_CHASSIS_REPORT_TIMEOUT = 43105;
constexpr int FM_LOC_FUSON_CHASSIS_REPORT_ABNORMAL = 43106;
constexpr int FM_LOC_FUSON_GET_CALIBPARAM_EMPTY = 43107;
constexpr int FM_LOC_FUSON_GET_CALIBPARAM_NOT_OK = 43108;
constexpr int FM_LOC_FUSION_NO_VECTOR_LOC = 43109;
constexpr int FM_LOC_FUSION_NO_LIDAR_LOC = 43110;
constexpr int FM_LOC_FUSION_STATUS_ERROR = 43113;
constexpr int FM_LOC_FUSION_NO_SMOOTH_LOC = 43114;
constexpr int FM_LOC_FUSION_ERROR_LOC = 43115;
constexpr int FM_LOC_LOC_LIDAR_GET_FUSION_POSE_FAIL = 43201;
constexpr int FM_LOC_LOC_LIDAR_GET_ODOM_FAIL = 43202;
constexpr int FM_LOC_LOC_LIDAR_WAIT_LIDAR_DATA = 43203;
constexpr int FM_LOC_LOC_LIDAR_PARSE_LIDAR_DATA_FAIL = 43204;
constexpr int FM_LOC_LOC_LIDAR_LOAD_MAP_FAIL = 43205;
constexpr int FM_LOC_LOC_LIDAR_FUSION_POSE_TIME_ERROE = 43206;
constexpr int FM_LOC_LOC_LIDAR_ODOM_TIME_ERROR = 43207;
constexpr int FM_LOC_LOC_LIDAR_LIDAR_TIME_ERROR = 43208;
constexpr int FM_LOC_LOC_LIDAR_FSM_TIME_ERROR = 43210;
constexpr int FM_LOC_LOC_LIDAR_SYSTEM_STATE_ERROR = 43211;
constexpr int FM_LOC_LOC_LODOM_NO_POINT_CLOUD = 43310;
constexpr int FM_LOC_LOC_LODOM_NO_ODOM_POSE = 43311;
constexpr int FM_LOC_LOC_LODOM_TIME_ODOM_POSE = 43312;
constexpr int FM_LOC_LOC_LODOM_TIME_LIDAR_POSE = 43313;
constexpr int FM_LOC_LOC_LODOM_TIME_FSM_STATE = 43314;

//FM_LOC_CALIB_XXX    44001-44500
constexpr int FM_LOC_CALIB_LOAD_FILE = 44001;
constexpr int FM_LOC_CALIB_CHECK_PARAMS = 44002;
constexpr int FM_LOC_CALIB_GUARD_CHECK_FRONT_WIDE_CAM_PARAMS = 44004;
constexpr int FM_LOC_CALIB_GUARD_CHECK_FRONT_WIDE_LANELINE = 44005;

//FM_LOC_RC_XXX    45001-45500
constexpr int FM_LOC_RoadCognition_NO_FUSION_LOC = 45001;
constexpr int FM_LOC_RoadCognition_NO_RELATIVE_LOC = 45002;
constexpr int FM_LOC_RoadCognition_NO_CALIBPARAM = 45003;
constexpr int FM_LOC_RoadCognition_FUSION_NO_VECTOR_LOC = 45004;
constexpr int FM_LOC_RoadCognition_RELATIVE_LOC_STAMP_ABNORMAL = 45005;
constexpr int FM_LOC_RoadCognition_NO_NAV_LOCAL_MAP = 45006;
constexpr int FM_LOC_RoadCognition_NAV_LOCAL_MAP_NOT_AVAILABLE = 45007;
constexpr int FM_LOC_RoadCognition_NO_NAV_MAP_MATCHING = 45008;
constexpr int FM_LOC_RoadCognition_NAV_MAP_MATCHING_ERROR = 45009;
constexpr int FM_LOC_RoadCognition_NO_TRAFFIC_LANE = 45010;
constexpr int FM_LOC_RoadCognition_TRAFFIC_LANE_STAMPE_ABNORMAL = 45011;
constexpr int FM_LOC_RoadCognition_NO_TRAFFIC_LIGHT = 45012;
constexpr int FM_LOC_RoadCognition_TRAFFIC_LIGHT_STAMP_ABNORMAL = 45013;
constexpr int FM_LOC_RoadCognition_REALISTIC_CHANGE = 45014;

//FM_PNC_PREDICTION_XXX    46001-46500
constexpr int FM_PNC_PREDICTION_RCV_FUSION_OBJECTS_TIMEOUT = 46001;
constexpr int FM_PNC_PREDICTION_RCV_LOC_TIMEOUT = 46011;
constexpr int FM_PNC_PREDICTION_RCV_LOC_ABNORMAL = 46012;
constexpr int FM_PNC_PREDICTION_RCV_FSM_TIMEOUT = 46021;
constexpr int FM_PNC_PREDICTION_RCV_ROAD_COGNITION_NCA_TIMEOUT = 46031;
constexpr int FM_PNC_PREDICTION_RCV_ROAD_COGNITION_NCA_ABNORMAL = 46032;

//FM_PNC_PLANNING_XXX    47001-47500
constexpr int FM_PNC_ROUTE_RCV_LOCALMAP_TIMEOUT = 47001;
constexpr int FM_PNC_ROUTE_RCV_EGO_TF_RELATIVE_TIMEOUT = 47002;
constexpr int FM_PNC_ROUTE_RCV_FSM_TIMEOUT = 47003;
constexpr int FM_PNC_ROUTE_RCV_EGO_TF_RELATIVE_ABNORMAL = 47004;
constexpr int FM_PNC_ROUTE_CURRENT_ROAD_TOO_FAR = 47006;
constexpr int FM_PNC_BDM_RCV_FSM_TIMEOUT = 47101;
constexpr int FM_PNC_BDM_RCV_FSM_ABNORMAL = 47102;
constexpr int FM_PNC_BDM_RCV_ROUTE_TIMEOUT = 47103;
constexpr int FM_PNC_BDM_RCV_ROUTE_ABNORMAL = 47104;
constexpr int FM_PNC_BDM_RCV_PREDICTION_TIMEOUT = 47105;
constexpr int FM_PNC_BDM_RCV_EGO_TF_RELATIVE_TIMEOUT = 47106;
constexpr int FM_PNC_BDM_RCV_EGO_TF_RELATIVE_ABNORMAL = 47107;
constexpr int FM_PNC_BDM_FORWARD_SIM_ABNORMAL = 47108;
constexpr int FM_PNC_IDM_RCV_ROUTE_TIMEOUT = 47201;
constexpr int FM_PNC_IDM_RCV_ROUTE_ABNORMAL = 47202;
constexpr int FM_PNC_IDM_RCV_CONTROL_COMMAND_TIMEOUT = 47203;
constexpr int FM_PNC_IDM_RCV_CONTROL_COMMAND_ABNORMAL = 47204;
constexpr int FM_IDM_EMERGANCY_CUTIN = 47205;
constexpr int FM_IDM_DANGEROUS_GRABWAY = 47206;
constexpr int FM_MOP_APA_PLAN_FAILED = 47301;
constexpr int FM_MOP_APA_LOCALIZATION_TIMEOUT = 47303;
constexpr int FM_MOP_APA_CHASSIS_TIMEOUT = 47304;
constexpr int FM_MOP_APA_SLOT_CHANGE_TOO_LARGE = 47305;
constexpr int FM_MOP_APA_STOP_DUTO_OBSTACLE = 47306;
constexpr int FM_PNC_MOP_RCV_PARKING_SLOT_TIMEOUT = 47307;
constexpr int FM_PNC_MOP_RCV_PARKING_SLOT_ABNORMAL = 47308;
constexpr int FM_PNC_MOP_RCV_LOCALMAP_OGM_TIMEOUT = 47309;
constexpr int FM_PNC_MOP_RCV_LOCALMAP_OGM_ABNORMAL = 47310;
constexpr int FM_MOP_LMOP_PREPROCESS_FAILED = 47321;
constexpr int FM_MOP_LMOP_CREATE_BOUND_XREF_FAILED = 47322;
constexpr int FM_MOP_LMOP_FIRST_OPTIMIZER_FAILED = 47323;
constexpr int FM_MOP_LMOP_SECOND_OPTIMIZER_FAILED = 47324;
constexpr int FM_MOP_LMOP_THIRD_OPTIMIZER_FAILED = 47325;
constexpr int FM_PNC_MOP_PLANNED_PATH_OVER_BOUNDARY = 47326;
constexpr int FM_PNC_LMOP_PATH_CURVATURE_OVER_LIMIT = 47327;
constexpr int FM_SMOP_INITPOINT_REPLANED = 47351;
constexpr int FM_SMOP_SL_PROJECTION_ERROR = 47352;
constexpr int FM_SMOP_INITSPEED_LOWER_THAN_EGOSPEED = 47353;
constexpr int FM_SMOP_OBSTACLE_BOX_CORNER_SL_CAL_FAILED = 47354;
constexpr int FM_SMOP_PERCEPTION_TIME_DELAY_OVER_400MS = 47355;
constexpr int FM_SMOP_FIRST_POINT_S_LOWER_THAN_SBOUND = 47356;
constexpr int FM_PNC_MOP_ANTICLOLLISION_ACCEL_OVER_LIMIT = 47357;
constexpr int FM_PNC_MOP_TTC_LOWER_THAN_LIMIT = 47358;
constexpr int FM_PNC_MOP_RCV_CHASSIS_TIMEOUT = 47381;
constexpr int FM_PNC_MOP_RCV_CHASSIS_ABNORMAL = 47382;
constexpr int FM_PNC_MOP_RCV_FSM_TIMEOUT = 47383;
constexpr int FM_PNC_MOP_RCV_FSM_ABNORMAL = 47384;
constexpr int FM_PNC_MOP_RCV_EGO_RELATIVE_TIMEOUT = 47385;
constexpr int FM_PNC_MOP_RCV_EGO_RELATIVE_ABNORMAL = 47386;
constexpr int FM_PNC_MOP_RCV_OBJECT_TIMEOUT = 47387;
constexpr int FM_PNC_MOP_RCV_OBJECT_ABNORMAL = 47388;
constexpr int FM_PNC_MOP_RCV_BDM_TIMEOUT = 47389;
constexpr int FM_PNC_MOP_RCV_BDM_ABNORMAL = 47390;
constexpr int FM_PNC_MOP_RCV_IDM_ABNORMAL = 47391;

//FM_PNC_CONTROL_XXX    48001-48500
constexpr int FM_PNC_CONTROL_RCV_MOP_TIMEOUT = 48002;
constexpr int FM_PNC_CONTROL_RCV_MOP_ABNORMAL = 48003;
constexpr int FM_PNC_CONTROL_RCV_MOP_EMPTY = 48004;
constexpr int FM_PNC_CONTROL_RCV_LOC_TIMEOUT = 48005;
constexpr int FM_PNC_CONTROL_RCV_LOC_ABNORMAL = 48006;
constexpr int FM_PNC_CONTROL_RCV_LOC_ERROR = 48007;
constexpr int FM_PNC_CONTROL_RCV_LOC_SHAPE_CHANGE = 48008;
constexpr int FM_PNC_CONTROL_RCV_CHASSIS_TIMEOUT = 48009;
constexpr int FM_PNC_CONTROL_RCV_CHASSIS_ABNORMAL = 48010;
constexpr int FM_PNC_CONTROL_LON_PREPROCESS_ABNORMAL = 48011;
constexpr int FM_PNC_CONTROL_LAT_PREPROCESS_ABNORMAL = 48012;
constexpr int FM_PNC_CONTROL_LON_SOLVE_ABNORMAL = 48013;
constexpr int FM_PNC_CONTROL_LAT_SOLVE_ABNORMAL = 48014;
constexpr int FM_PNC_CONTROL_LON_SOLVE_FAIL = 48015;
constexpr int FM_PNC_CONTROL_LAT_SOLVE_FAIL = 48016;
constexpr int FM_PNC_CONTROL_ACCEL_FOLLOW_ABNORMAL = 48017;
constexpr int FM_PNC_CONTROL_STEER_FOLLOW_ABNORMAL = 48018;
constexpr int FM_PNC_CONTROL_SPEED_FOLLOW_ABNORMAL = 48019;
constexpr int FM_PNC_CONTROL_CURVE_LARGE_ABNORMAL = 48021;
constexpr int FM_PNC_CONTROL_CURVE_CHANGE_ABNORMAL = 48022;
constexpr int FM_PNC_CONTROL_NOT_START_UP_ABNORMAL = 48023;
constexpr int FM_PNC_WIRE_CONTROL_RCV_FSM_TIMEOUT = 48100;
constexpr int FM_PNC_WIRE_CONTROL_RCV_CONTROL_TIMEOUT = 48101;
constexpr int FM_PNC_WIRE_CONTROL_RCV_MCU_TIMEOUT = 48102;
constexpr int FM_PNC_WIRE_CONTROL_SEND_ACCEL_ABNORMAL = 48103;
constexpr int FM_PNC_WIRE_CONTROL_SEND_LON_ACTIVE_ABNORMAL = 48104;
constexpr int FM_PNC_WIRE_CONTROL_SEND_STEER_ABNORMAL = 48105;
constexpr int FM_PNC_WIRE_CONTROL_SEND_LAT_ACTIVE_ABNORMAL = 48106;
constexpr int FM_PNC_WIRE_CONTROL_CAN_BUS_LOST = 48107;
constexpr int FM_PNC_WIRE_CONTROL_CAN_QF_ERR = 48108;
constexpr int FM_PNC_WIRE_CONTROL_CAN_E2E_ERR = 48109;
constexpr int FM_PNC_WIRE_CONTROL_RCV_SOC_TIMEOUT = 48110;
constexpr int FM_PNC_FSM_RCV_CHASSIS_TIMEOUT = 48300;
constexpr int FM_PNC_FSM_RCV_BODY_TIMEOUT = 48301;
constexpr int FM_PNC_FSM_RCV_WIRE_CONTROL_TIMEOUT = 48302;
constexpr int FM_PNC_FSM_RCV_CONTROL_TIMEOUT = 48303;
constexpr int FM_PNC_FSM_RCV_MOP_TIMEOUT = 48304;
constexpr int FM_PNC_FSM_RCV_IDM_TIMEOUT = 48305;
constexpr int FM_PNC_FSM_RCV_BDM_TIMEOUT = 48306;
constexpr int FM_PNC_FSM_RCV_ROUTE_TIMEOUT = 48307;
constexpr int FM_PNC_FSM_RCV_PREDICTION_TIMEOUT = 48308;
constexpr int FM_PNC_FSM_RCV_HMI_TIMEOUT = 48309;
constexpr int FM_PNC_FSM_RCV_LOC_TIMEOUT = 48310;
constexpr int FM_PNC_FSM_RCV_LOC_ERROR = 48312;
constexpr int FM_PNC_FSM_RCV_LOC_WARNING = 48313;
constexpr int FM_PNC_FSM_CHASSIS_ABNORMAL = 48314;
constexpr int FM_PNC_FSM_LATERAL_CONTROL_ABNORMAL = 48315;
constexpr int FM_PNC_FSM_HAND_TORQUE_EXCEED = 48316;
constexpr int FM_PNC_FSM_BRAKE_PRESSED = 48317;
constexpr int FM_PNC_FSM_CRUISE_ACTIVE_WHILE_APA = 48318;
constexpr int FM_PNC_FSM_ROUTE_NOT_AVAIALABLE_NCA = 48319;
constexpr int FM_PNC_FSM_PARKING_STATUS_ABNORMAL = 48321;
constexpr int FM_PNC_FSM_APA_SPEED_EXCEED = 48322;
constexpr int FM_PNC_FSM_SEATBELT_RELEASE = 48323;
constexpr int FM_PNC_FSM_SEATBELT_UNLOCK = 48324;
constexpr int FM_PNC_FSM_DRIVER_NOT_ON_SEAT = 48325;
constexpr int FM_PNC_FSM_ACTIVATED_ALREADY = 48326;
constexpr int FM_PNC_FSM_ROUTE_NOT_AVAIALABLE_ACTIVATE = 48327;

//FM_HMI_XXX    49001-49500

//FM_ZDI_XXX    52801-52900

//FM_NAVI_XXX    53000-53500
constexpr int MAP_SDK_ROM_ABNOMAL_HOT = 53001;
constexpr int MAP_SDK_ROM_ABNOMAL_COLD = 53002;
constexpr int MAP_4G_SIGNAL_MISSING = 53003;
constexpr int MAP_SDK_NO_UID = 53004;
constexpr int MAP_SDK_INTERNAL_FAILURE = 53005;
constexpr int MAP_SDK_V3_DATA_STORAGE_ROUTE_ABNORMAL = 53006;
constexpr int MAP_SDK_V3_READ_AND_WRITE_ACCESS_ABNORMAL = 53007;
constexpr int MAP_SDK_API_EHPV3_INTERNAL_FAILURE = 53008;
constexpr int MAP_SDK_API_EHPV3_DATA_STORAGE_ROUTE_ABNORMAL = 53009;
constexpr int MAP_SDK_API_EHPV3_READ_AND_WRITE_ACCESS_ABNORMAL = 53010;
constexpr int MAP_SDK_LICENSE_NONACTIVATED_OR__EXPIRED = 53011;
constexpr int AMAP_INITIALIZATION_FAILED = 53012;
constexpr int LOCALIZATION_SIGNAL_MISSING = 53013;

//FM_ADPU_DRV_XXX    49601-49900
constexpr int FM_ADPU_DRV_NOT_SYNC = 49601;
constexpr int FM_ADPU_DRV_INS_FRAME_DROPPED = 49602;
constexpr int FM_ADPU_DRV_GNSS_FRAME_DROPPED = 49603;
constexpr int FM_ADPU_DRV_IMU_FRAME_DROPPED = 49604;
constexpr int FM_ADPU_DRV_PERIODIC_ANOMALY = 49605;
constexpr int FM_ADPU_DRV_SEND_ERROR = 49606;
constexpr int FM_ADPU_DRV_ID_PASS_THROUGH = 49607;
constexpr int FM_ADPU_DRV_E2E_CHECK_FAIL = 49608;

//FM_DVR_XXX    50001-50100

//FM_VGM_XXX    50201-50300

//FM_TCAM_XXX    50401-50500

//FM_CEM_XXX    50601-50700

//FM_BCM_XXX    50801-50900

//FM_RBCM_XXX    51001-51100

//FM_SRS_XXX    51201-51300

//FM_RML_XXX    51401-51500

//FM_PCMU_XXX    51601-51700

//FM_PSCM1_XXX    51801-51900

//FM_PSCM2_XXX    52001-52100

//FM_SAS_XXX    52201-52300

//FM_DHU_XXX    52401-52500

//FM_DMM_XXX    52601-52700

//FM_SUM_XXX    52701-52800


}
}

#endif
