/******************************************************************************
 * Copyright (c) 2022-2022 by ZEEKR. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * @Brief:
 * @Author:Liting.Yin
 * @Date:2022-11-22
 *****************************************************************************/
#ifndef ZPILOT_ZDRIVE_MODULE_ID_H_
#define ZPILOT_ZDRIVE_MODULE_ID_H_

/**
 * @brief 跟ini配置中的moduleId值保持一一对应，意味着枚举变量的先后顺序不可轻易改变
 */

typedef enum EModuleId {
    MODULE_INVALID = -1,

    MODULE_MCU_START = 0,  // 德赛 [1, 999]
    MODULE_MCU_LOG_RECEIVER_ID,
    MODULE_MCU_CTAPWIRECONTROLCHASSISTX_ID,
    MODULE_MCU_CTAPWIRECONTROLCHASSISRX_ID,
    MODULE_MCU_CTAPFAULTMANAGER_ID,
    MODULE_MCU_CTAPFUNCTIONSTATEMANAGER_ID,
    MODULE_MCU_CTAPAPSAFELIMITATION_ID,
    MODULE_MCU_CTAPHMI_ID,
    MODULE_MCU_CTAPCONTROLARTRIBUTION_ID,
    MODULE_MCU_CTAPWIRECONTROLBODYTX_ID,
    MODULE_MCU_CTAPWIRECONTROLBODYRX_ID,
    MODULE_MCU_CTAPDDSCOM_ID,
    MODULE_MCU_CTAPNVM_ID,
    MODULE_MCU_END = 1000, // end flag of mcu

    MODULE_PLATFORM_START = 1001, // 软件平台 [1001, 1999]
    MODULE_OPER_ID,
    MODULE_SECURE_ID,
    MODULE_FAULT_ID,
    MODULE_PERF_ID,
    MODULE_HMI_SERVER_ID = 1101,
    MODULE_HMI_PUSH_STREAM_ID,
    MODULE_HMI_SRS_ID,
    MODULE_DRIVER_UPDATE_ID = 1110,
    MODULE_ZDI_GATEWAY_ID,
    MODULE_ZDI_OTA_ID,
    MODULE_ZDI_COMMAND_SUBSCRIBER_ID,
    MODULE_ZDI_EHR_ID,
    MODULE_DRIVER_CAMERA_ID = 1120,
    MODULE_DRIVER_RADAR_CONTI510_ID,
    MODULE_DRIVER_RADAR_CONTI520_ID,
    MODULE_DRIVER_DRIVER_SMART_CAMERA_ID,
    MODULE_DRIVER_ID,
    MODULE_DRIVER_INS_ID,
    MODULE_DRIVER_LIDAR_ID,
    MODULE_DRIVER_USS_ID,
    MODULE_OM_ZPROF_ID = 1130,
    MODULE_OM_LOG_AGENT_ID,
    MODULE_OM_LOG_SERVER_ID,
    MODULE_OM_CFG_SERVER_ID,
    MODULE_OM_FAULT_MANAGER_ID,
    MODULE_OM_MONITOR_ID,
    MODULE_OM_COLLECTOR_ID,
    MODULE_PLATFORM_END = 2000, // end flag of platform

    MODULE_PERCP_START = 2001, // 感知融合 [2001, 2999]
    MODULE_PERCP_RADAR_FUSION_ID,
    MODULE_PERCP_TARGET_FUSION_ID,
    MODULE_PERCP_TRAFFICLANE_ID,
    MODULE_PERCP_VISION_OBJECT_ID,
    MODULE_PERCP_IPM_NN_ID,
    MODULE_PERCP_LIDAR_OBJECT_ID,
    MODULE_PERCP_LOCALMAP_ID,
    MODULE_PERCP_PARKING_SLOT_ID,
    MODULE_PERCP_PERCP_USS_FUSION_ID,
    MODULE_PERCP_WORLD_MODEL_ID,
    MODULE_PERCP_END = 3000, // end flag of percp

    MODULE_MAP_START = 3001,    // 构图定位 [3001, 3999]
    MODULE_MAP_CALIB_GUARD_ID,
    MODULE_MAP_CALIB_SERVER_ID,
    MODULE_MAP_ENCRYPT_PLUGIN_ID,
    MODULE_MAP_NAV_ID,
    MODULE_MAP_SCENE_MAPPING_ID,
    MODULE_LOC_FUSION_ID,
    MODULE_LOC_LIDAR_ID,
    MODULE_LOC_LODOM_ID,
    MODULE_RELATIVE_LOC_ID,
    MODULE_MAP_END = 4000, // end flag of map

    MODULE_PNC_START = 4001,    // 规划控制 [4001, 4999]
    MODULE_PNC_AEB_ID,
    MODULE_PNC_BDM_ID,
    MODULE_PNC_CONTROL_ID,
    MODULE_PNC_FSM_ID,
    MODULE_PNC_MOP_ID,
    MODULE_PNC_PREDICTION_ID,
    MODULE_PNC_ROUTE_ID,
    MODULE_PNC_WIRE_CONTROL_ID,
    MODULE_PNC_END = 5000, // end flag of pnc
} EModuleId;

#endif
